name: Push

on:
  push:
    branches: [main]

env:
  TF_VERSION: 0.14.7
  TG_VERSION: 0.26.7
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: dev

jobs:
  ci:
    name: ci
    runs-on: ubuntu-20.04
    environment: dev

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Install packages
        run: |
          cd ./lambda && \
          for d in */ ; do
            cd $d && \
            npm i && \
            cd ..
          done

      - name: Install Zip
        uses: montudor/action-zip@v1

      - name: Make artifact directory
        run: mkdir artifacts

      - name: Processing my found files from output
        run: |
          cd ./lambda && \
          for d in */ ; do
            zip -qq -r ../artifacts/${d::-1}.zip $d
          done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          role-duration-seconds: 900
          role-session-name: parks-reso-admin-dev-gh-action
          role-skip-session-tagging: true

      - name: Upload zips to S3
        run: |
          aws s3 sync ./artifacts s3://${{secrets.AWS_S3_BUCKET_DEV}}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - name: Terragrunt Apply
        working-directory: ${{ env.TG_SRC_PATH }}/${{ env.TFC_WORKSPACE }}
        env:
          app_version: ${{ github.run_number }}
        run: terragrunt apply-all --terragrunt-non-interactive